// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuIFITpq52Res2hG9TEZorKryu92U0lCI',
    appId: '1:965213168409:web:4e505f19df784631985b88',
    messagingSenderId: '965213168409',
    projectId: 'feafa-b9aef',
    authDomain: 'feafa-b9aef.firebaseapp.com',
    storageBucket: 'feafa-b9aef.appspot.com',
    measurementId: 'G-WSS1L47GJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3ww563A76jGxfMRWdjYqs2axzFT6Y7M',
    appId: '1:965213168409:android:0f49523ab455259b985b88',
    messagingSenderId: '965213168409',
    projectId: 'feafa-b9aef',
    storageBucket: 'feafa-b9aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-aQWvgn_At4s4a_jpEqLIFTdZSOELQfE',
    appId: '1:965213168409:ios:d72d19d54494bb3f985b88',
    messagingSenderId: '965213168409',
    projectId: 'feafa-b9aef',
    storageBucket: 'feafa-b9aef.appspot.com',
    iosBundleId: 'com.example.pictodi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-aQWvgn_At4s4a_jpEqLIFTdZSOELQfE',
    appId: '1:965213168409:ios:a9e3ba682b3b83e7985b88',
    messagingSenderId: '965213168409',
    projectId: 'feafa-b9aef',
    storageBucket: 'feafa-b9aef.appspot.com',
    iosBundleId: 'com.example.pictodi2.RunnerTests',
  );
}
